# categories

# Список всех категорий
GET http://127.0.0.1:3000/api/categories  HTTP/1.1

###

# articles

# Список публикаций

GET http://127.0.0.1:3000/api/articles  HTTP/1.1

###

# Публикация

GET http://127.0.0.1:3000/api/articles/YIkbZd  HTTP/1.1

###

# Создать публикацию
POST http://127.0.0.1:3000/api/articles HTTP/1.1
Content-Type: application/json

{
  "title": "Новая публикация",
  "createdDate": "2021-04-25 22:47:22",
  "announce": "Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать. Вы можете достичь всего. Стоит только немного постараться и запастись книгами. Достичь успеха помогут ежедневные повторения. Как начать действовать? Для начала просто соберитесь. Игры и программирование разные вещи. Не стоит идти в программисты, если вам нравятся только игры.",
  "fullText": "Это один из лучших рок-музыкантов. Достичь успеха помогут ежедневные повторения.",
  "сategory": ["Разное"]
}

###

# Редактировать публикацию
PUT http://127.0.0.1:3000/api/articles/9SwdjM HTTP/1.1
Content-Type: application/json

{
  "title": "Эта публицая изменена",
  "createdDate": "2021-04-25 22:47:22",
  "announce": "Альбом стал настоящим открытием года. Мощные гитарные рифы и скоростные соло-партии не дадут заскучать. Вы можете достичь всего. Стоит только немного постараться и запастись книгами. Достичь успеха помогут ежедневные повторения. Как начать действовать? Для начала просто соберитесь. Игры и программирование разные вещи. Не стоит идти в программисты, если вам нравятся только игры.",
  "fullText": "Это один из лучших рок-музыкантов. Достичь успеха помогут ежедневные повторения.",
  "сategory": ["Разное"]
}

###

# Удалить публикацию
DELETE http://127.0.0.1:3000/api/articles/9SwdjM HTTP/1.1

###

# Список комментариев публикации

GET http://127.0.0.1:3000/api/articles/Gt29r9/comments  HTTP/1.1

###

# Удаление комментария

DELETE http://127.0.0.1:3000/api/articles/Gt29r9/comments/lEnJtD  HTTP/1.1

###

# Новый комментарий

POST http://127.0.0.1:3000/api/articles/Gt29r9/comments  HTTP/1.1
Content-Type: application/json

{
  "text": "НОВЫЙ КОММЕНТ"
}

# search

###

# Поиск
GET http://127.0.0.1:3000/api/search?query=Что такое HTTP/1.1

# comments

###

# Список всех комментариев
GET http://127.0.0.1:3000/api/comments HTTP/1.1
